// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crvjomebcgglupzslpbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNydmpvbWViY2dnbHVwenNscGJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MTA2MTksImV4cCI6MjA2Nzk4NjYxOX0.tfSyLEjgZQXTbDn9YDH1fbrP69qe2LdXQKqHFomGZTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});